/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.11
 * Generated at: 2021-11-21 02:29:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.*;
import com.exam.helper.ConnectionProvider;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/normal_navbar.jsp", Long.valueOf(1635657571231L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.exam.helper.ConnectionProvider");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"error_page.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<title>Hello, world!</title>\r\n");
      out.write("\r\n");
      out.write("<!-- CSS -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\"\r\n");
      out.write("	integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<link href=\"css/mystyle.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".banner-background {\r\n");
      out.write("	clip-path: polygon(100% 0, 100% 100%, 77% 98%, 65% 96%, 49% 100%, 37% 96%, 24% 99%,\r\n");
      out.write("		0 100%, 0 0);\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!--navbar-->\r\n");
      out.write("	");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark primary-background\">\r\n");
      out.write("    <a class=\"navbar-brand\" href=\"index.jsp\"><span class=\"fa fa-asterisk\"></span>OEWP</a>\r\n");
      out.write("    <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("        <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("    </button>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("        <ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("            <li class=\"nav-item active\" id=\"nav_practice\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"login_page.jsp\"><span class=\"fa fa-bell-o\"></span>Practice <span class=\"sr-only\">(current)</span></a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\" id=\"nav_contact\">\r\n");
      out.write("                <a class=\"nav-link\"  href=\"#!\"\r\n");
      out.write("					data-toggle=\"modal\" data-target=\"#contact-modal\"><span class=\"fa fa-address-card\"></span>Contact</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\" id=\"nav_login\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"login_page.jsp\"><span class=\"fa fa-user-circle\"></span>Login</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\" id=\"nav_register\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"register_page.jsp\"><span class=\"fa fa-user-plus\"></span>Sign Up</a>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <form class=\"form-inline my-2 my-lg-0\">\r\n");
      out.write("            <input class=\"form-control mr-sm-2\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\">\r\n");
      out.write("            <button class=\"btn btn-outline-light my-2 my-sm-0\" type=\"submit\">Search</button>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Contact modal -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Button trigger modal -->\r\n");
      out.write("	<!-- <button type=\"button\" class=\"btn btn-primary\" data-toggle=\"modal\"\r\n");
      out.write("		data-target=\"#exampleModal\">Launch demo modal</button> -->\r\n");
      out.write("\r\n");
      out.write("	<!-- Modal -->\r\n");
      out.write("	<div class=\"modal fade\" id=\"contact-modal\" tabindex=\"-1\" role=\"dialog\"\r\n");
      out.write("		aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("		<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("				<div class=\"modal-header primary-background text-white text-center\">\r\n");
      out.write("					<h5 class=\"modal-title\" id=\"exampleModalLabel\">Contact Us</h5>\r\n");
      out.write("					<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("						aria-label=\"Close\">\r\n");
      out.write("						<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("					</button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-body\">\r\n");
      out.write("\r\n");
      out.write("					<div class=\"container-fluid\">\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<div class=\"col-md-4\">\r\n");
      out.write("								<h6>Email us at:</h6>\r\n");
      out.write("								<h6>Call us at:</h6>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-md-8\">\r\n");
      out.write("								<h6>\r\n");
      out.write("									<a href=\"mailto:me.sakshi.021@gmail.com\"><i\r\n");
      out.write("										class=\"fa fa-at\"></i>me.sakshi.021@gmail.com</a>\r\n");
      out.write("								</h6>\r\n");
      out.write("								<h6>\r\n");
      out.write("									<i class=\"fa fa-mobile\"></i>+91 7079729758\r\n");
      out.write("								</h6>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<hr>\r\n");
      out.write("					<form action=\"SubmitQuery\" method=\"post\" id=\"query-form\">\r\n");
      out.write("\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<label for=\"subject\">Subject</label> <input name=\"subject\"\r\n");
      out.write("								required type=\"text\" class=\"form-control\" id=\"subject\"\r\n");
      out.write("								aria-describedby=\"emailHelp\" placeholder=\"Subject\">\r\n");
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<label for=\"description\">Description</label>\r\n");
      out.write("							<textarea name=\"description\" class=\"form-control\" rows=\"5\"\r\n");
      out.write("								placeholder=\"Description\"></textarea>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<button type=\"submit\" class=\"btn btn-primary\"\r\n");
      out.write("							style=\"float: right;\">Submit your Query</button>\r\n");
      out.write("					</form>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- <div class=\"modal-footer\">\r\n");
      out.write("					<button type=\"button\" class=\"btn btn-secondary\"\r\n");
      out.write("						data-dismiss=\"modal\">Close</button>\r\n");
      out.write("				</div> -->\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- end of contact modal -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Carousel -->\r\n");
      out.write("\r\n");
      out.write("	<div id=\"carouselExampleIndicators\" class=\"carousel slide my-0 py-0\"\r\n");
      out.write("		data-ride=\"carousel\">\r\n");
      out.write("		<ol class=\"carousel-indicators\">\r\n");
      out.write("			<li data-target=\"#carouselExampleIndicators\" data-slide-to=\"0\"\r\n");
      out.write("				class=\"active\"></li>\r\n");
      out.write("			<li data-target=\"#carouselExampleIndicators\" data-slide-to=\"1\"></li>\r\n");
      out.write("			<li data-target=\"#carouselExampleIndicators\" data-slide-to=\"2\"></li>\r\n");
      out.write("		</ol>\r\n");
      out.write("		<div class=\"carousel-inner\">\r\n");
      out.write("			<div class=\"carousel-item active\">\r\n");
      out.write("				<img class=\"d-block w-100\" src=\"img/one.jfif\" alt=\"First slide\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"carousel-item\">\r\n");
      out.write("				<img class=\"d-block w-100\" src=\"img/two.jfif\" alt=\"Second slide\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"carousel-item\">\r\n");
      out.write("				<img class=\"d-block w-100\" src=\"img/three.jfif\" alt=\"Third slide\">\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<a class=\"carousel-control-prev\" href=\"#carouselExampleIndicators\"\r\n");
      out.write("			role=\"button\" data-slide=\"prev\"> <span\r\n");
      out.write("			class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span> <span\r\n");
      out.write("			class=\"sr-only\">Previous</span>\r\n");
      out.write("		</a> <a class=\"carousel-control-next\" href=\"#carouselExampleIndicators\"\r\n");
      out.write("			role=\"button\" data-slide=\"next\"> <span\r\n");
      out.write("			class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span> <span\r\n");
      out.write("			class=\"sr-only\">Next</span>\r\n");
      out.write("		</a>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- end of carousel -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!--Banner-->\r\n");
      out.write("	<div class=\"container-fluid m-0 p-0\">\r\n");
      out.write("		<div\r\n");
      out.write("			class=\"jumbotron primary-background text-white banner-background mt-0 pt-0\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<h3 class=\"display-3 text-center\">Welcome to OEWP</h3>\r\n");
      out.write("				<p>Welcome to technical blog, world of technology A programming\r\n");
      out.write("					language is a formal language comprising a set of strings that\r\n");
      out.write("					produce various kinds of machine code output. Programming languages\r\n");
      out.write("					are one kind of computer language, and are used in computer\r\n");
      out.write("					programming to implement algorithms.</p>\r\n");
      out.write("				<p>Most programming languages consist of instructions for\r\n");
      out.write("					computers. There are programmable machines that use a set of\r\n");
      out.write("					specific instructions, rather than general programming languages.\r\n");
      out.write("					Since the early 1800s, programs have been used to direct the\r\n");
      out.write("					behavior of machines such as Jacquard looms, music boxes and player\r\n");
      out.write("					pianos.[1] The programs for these machines (such as a player\r\n");
      out.write("					piano's scrolls) did not produce different behavior in response to\r\n");
      out.write("					different inputs or conditions.</p>\r\n");
      out.write("\r\n");
      out.write("				<a href=\"register_page.jsp\" class=\"btn btn-outline-light btn-lg\">\r\n");
      out.write("					<span class=\"fa fa-user-plus\"></span> Start! Its Free\r\n");
      out.write("				</a> <a href=\"login_page.jsp\" class=\"btn btn-outline-light btn-lg\">\r\n");
      out.write("					<span class=\"fa fa-user-circle fa-spin\"></span> Login\r\n");
      out.write("				</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container-fluid\">\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"col-md-3\">\r\n");
      out.write("				<button type=\"button\" class=\"btn btn-primary btn-block\">Events</button>\r\n");
      out.write("				<div class=\"jumbotron jumbotron-fluid p-2\"\r\n");
      out.write("					style=\"width: 100%; height: 300px;\">\r\n");
      out.write("					<p>\r\n");
      out.write("						Event<img src=\"img/new-gif-image.gif\" width=\"40\" />\r\n");
      out.write("					</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"col-md-6\"></div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"col-md-3\">\r\n");
      out.write("				<button type=\"button\" class=\"btn btn-primary btn-block\">News\r\n");
      out.write("					and Notices</button>\r\n");
      out.write("				<div class=\"jumbotron jumbotron-fluid p-2\"\r\n");
      out.write("					style=\"width: 100%; height: 300px;\">\r\n");
      out.write("					<p>\r\n");
      out.write("						News and Notice<img src=\"img/new-gif-image.gif\" width=\"40\" />\r\n");
      out.write("					</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- footer -->\r\n");
      out.write("\r\n");
      out.write("	<nav class=\"navbar navbar-dark bg-dark\">\r\n");
      out.write("		<div class=\"text-white mr-auto ml-auto\">OEWP | Copyright@2021</div>\r\n");
      out.write("	</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- JavaScript -->\r\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"\r\n");
      out.write("		integrity=\"sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=\"\r\n");
      out.write("		crossorigin=\"anonymous\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js\"\r\n");
      out.write("		integrity=\"sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q\"\r\n");
      out.write("		crossorigin=\"anonymous\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\"\r\n");
      out.write("		integrity=\"sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl\"\r\n");
      out.write("		crossorigin=\"anonymous\"></script>\r\n");
      out.write("	<script src=\"js/myjs.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
