/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.11
 * Generated at: 2021-12-16 09:52:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.exam.entities.Questions;
import java.util.ArrayList;
import com.exam.helper.ConnectionProvider;
import com.exam.dao.QuestionDao;
import com.exam.entities.User;

public final class questions_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.exam.helper.ConnectionProvider");
    _jspx_imports_classes.add("com.exam.dao.QuestionDao");
    _jspx_imports_classes.add("com.exam.entities.Questions");
    _jspx_imports_classes.add("com.exam.entities.User");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"error_page.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

User user = (User) session.getAttribute("currentUser");
if (user == null) {
	response.sendRedirect("login_page.jsp");
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<!-- CSS -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\"\r\n");
      out.write("	integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<link href=\"css/mystyle.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".banner-background {\r\n");
      out.write("	clip-path: polygon(0 0, 70% 0%, 100% 0, 99% 94%, 63% 100%, 31% 93%, 0 98%, 0% 30%);\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body onload=display_ct();>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!--navbar-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<nav class=\"navbar navbar-expand-lg navbar-dark primary-background\">\r\n");
      out.write("		<a class=\"navbar-brand\" href=\"index.jsp\"><span\r\n");
      out.write("			class=\"fa fa-asterisk\"></span>OEWP</a>\r\n");
      out.write("		<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
      out.write("			data-target=\"#navbarSupportedContent\"\r\n");
      out.write("			aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\r\n");
      out.write("			aria-label=\"Toggle navigation\">\r\n");
      out.write("			<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("		</button>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("			<ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("				<li class=\"nav-item active\"><a class=\"nav-link\" href=\"#\"><span\r\n");
      out.write("						class=\"fa fa-bell-o\"></span>");
      out.print(user.getName());
      out.write(" <span\r\n");
      out.write("						class=\"sr-only\">(current)</span></a></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			</ul>\r\n");
      out.write("			<ul class=\"navbar-nav mr-right\">\r\n");
      out.write("\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\" href=\"#!\"\r\n");
      out.write("					data-toggle=\"modal\" data-target=\"#contact-modal\"><span\r\n");
      out.write("						class=\"fa fa-address-card\"></span>Contact</a></li>\r\n");
      out.write("				<li class=\"nav-item\">\r\n");
      out.write("					<span id='ct' class=\"ml-2 text-light font-weight-light\"></span>\r\n");
      out.write("					<br>\r\n");
      out.write("					<span id=\"time\" class=\"ml-2 text-light font-weight-light\">05:00</span>\r\n");
      out.write("				</li>\r\n");
      out.write("\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("	</nav>\r\n");
      out.write("\r\n");
      out.write("	<!--end of navbar-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Contact modal -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Button trigger modal -->\r\n");
      out.write("	<!-- <button type=\"button\" class=\"btn btn-primary\" data-toggle=\"modal\"\r\n");
      out.write("		data-target=\"#exampleModal\">Launch demo modal</button> -->\r\n");
      out.write("\r\n");
      out.write("	<!-- Modal -->\r\n");
      out.write("	<div class=\"modal fade\" id=\"contact-modal\" tabindex=\"-1\" role=\"dialog\"\r\n");
      out.write("		aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("		<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("				<div class=\"modal-header primary-background text-white text-center\">\r\n");
      out.write("					<h5 class=\"modal-title\" id=\"exampleModalLabel\">Contact Us</h5>\r\n");
      out.write("					<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("						aria-label=\"Close\">\r\n");
      out.write("						<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("					</button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-body\">\r\n");
      out.write("\r\n");
      out.write("					<div class=\"container-fluid\">\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<div class=\"col-md-4\">\r\n");
      out.write("								<h6>Email us at:</h6>\r\n");
      out.write("								<h6>Call us at:</h6>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-md-8\">\r\n");
      out.write("								<h6>\r\n");
      out.write("									<a href=\"mailto:>me.sakshi.021@gmail.com\"><i\r\n");
      out.write("										class=\"fa fa-at\"></i>me.sakshi.021@gmail.com</a>\r\n");
      out.write("								</h6>\r\n");
      out.write("								<h6>\r\n");
      out.write("									<i class=\"fa fa-mobile\"></i>+91 7079729758\r\n");
      out.write("								</h6>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<hr>\r\n");
      out.write("					<form action=\"SubmitQuery\" method=\"post\" id=\"query-form\">\r\n");
      out.write("\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<label for=\"subject\">Subject</label> <input name=\"subject\"\r\n");
      out.write("								required type=\"text\" class=\"form-control\" id=\"subject\"\r\n");
      out.write("								aria-describedby=\"emailHelp\" placeholder=\"Subject\">\r\n");
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<label for=\"description\">Description</label>\r\n");
      out.write("							<textarea name=\"description\" class=\"form-control\" rows=\"5\"\r\n");
      out.write("								placeholder=\"Description\"></textarea>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<button type=\"submit\" class=\"btn btn-primary\"\r\n");
      out.write("							style=\"float: right;\">Submit your Query</button>\r\n");
      out.write("					</form>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- <div class=\"modal-footer\">\r\n");
      out.write("					<button type=\"button\" class=\"btn btn-secondary\"\r\n");
      out.write("						data-dismiss=\"modal\">Close</button>\r\n");
      out.write("				</div> -->\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- end of contact modal -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"jumbotron\">\r\n");
      out.write("\r\n");
      out.write("			<h2>OEWP - Online Examination Web Portal</h2>\r\n");
      out.write("			<p>Lorem Ipsum is simply dummy text of the printing and\r\n");
      out.write("				typesetting industry. Lorem Ipsum has been the industry's standard\r\n");
      out.write("				dummy text ever since the 1500s, when an unknown printer took a\r\n");
      out.write("				galley of type and scrambled it to make a type specimen book. It has\r\n");
      out.write("				survived not only five centuries, but also the leap into electronic\r\n");
      out.write("				typesetting, remaining essentially unchanged. It was popularised in\r\n");
      out.write("				the 1960s with the release of Letraset sheets containing Lorem Ipsum\r\n");
      out.write("				passages, and more recently with desktop publishing software like\r\n");
      out.write("				Aldus PageMaker including versions of Lorem Ipsum.</p>\r\n");
      out.write("			<hr style=\"border: 1px solid black;\">\r\n");
      out.write("			<div class=\"container-fluid\">\r\n");
      out.write("				<form action=\"QuestionServlet\" method=\"post\" id=\"question\">\r\n");
      out.write("					<ol>\r\n");
      out.write("\r\n");
      out.write("						");

						/* Integer c= 0;
						c = (Integer) session.getAttribute("cid");
						System.out.print(c);
						int cid = Integer.valueOf(c); */

						String c = session.getAttribute("cid").toString();
						int cid = Integer.parseInt(c);
						QuestionDao dao = new QuestionDao(ConnectionProvider.getConnection());
						ArrayList<Questions> list = dao.getQuestionsByCid(cid);
						for (Questions question : list) {
						
      out.write("\r\n");
      out.write("						<li class=\"lead\">");
      out.print(question.getQuestion());
      out.write("</li>\r\n");
      out.write("						<ol style=\"list-style-type: lower-roman;\">\r\n");
      out.write("\r\n");
      out.write("							<input type=\"radio\" name=\"");
      out.print(question.getQid());
      out.write("\" value=\"1\"\r\n");
      out.write("								required>\r\n");
      out.write("							");
      out.print(question.getOption1());
      out.write("\r\n");
      out.write("							<br>\r\n");
      out.write("							<input type=\"radio\" name=\"");
      out.print(question.getQid());
      out.write("\" value=\"2\"\r\n");
      out.write("								required>\r\n");
      out.write("							");
      out.print(question.getOption2());
      out.write("\r\n");
      out.write("							<br>\r\n");
      out.write("							<input type=\"radio\" name=\"");
      out.print(question.getQid());
      out.write("\" value=\"3\"\r\n");
      out.write("								required>\r\n");
      out.write("							");
      out.print(question.getOption3());
      out.write("\r\n");
      out.write("							<br>\r\n");
      out.write("							<input type=\"radio\" name=\"");
      out.print(question.getQid());
      out.write("\" value=\"4\"\r\n");
      out.write("								required>\r\n");
      out.write("							");
      out.print(question.getOption4());
      out.write("\r\n");
      out.write("\r\n");
      out.write("						</ol>\r\n");
      out.write("						<hr class=\"my-4\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						");

						}
						
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					</ol>\r\n");
      out.write("					<div class=\"float-right\">\r\n");
      out.write("						<button id=\"submit-btn\" type=\"submit\"\r\n");
      out.write("							onclick=\"return confirm('Want to Finish Exam?')\"\r\n");
      out.write("							class=\"btn primary-background text-white\">Submit Exam</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- JavaScript -->\r\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"\r\n");
      out.write("		integrity=\"sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=\"\r\n");
      out.write("		crossorigin=\"anonymous\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js\"\r\n");
      out.write("		integrity=\"sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q\"\r\n");
      out.write("		crossorigin=\"anonymous\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\"\r\n");
      out.write("		integrity=\"sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl\"\r\n");
      out.write("		crossorigin=\"anonymous\"></script>\r\n");
      out.write("	<script src=\"js/myjs.js\" type=\"text/javascript\"></script>\r\n");
      out.write("	<script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		function display_c(){\r\n");
      out.write("			var refresh=1000; // Refresh rate in milli seconds\r\n");
      out.write("			mytime=setTimeout('display_ct()',refresh)\r\n");
      out.write("		}\r\n");
      out.write("		function display_ct() {\r\n");
      out.write("			var x = new Date()\r\n");
      out.write("			var x1=x.getHours( )+ \":\" +  x.getMinutes() + \":\" +  x.getSeconds();\r\n");
      out.write("			document.getElementById('ct').innerHTML = x1;\r\n");
      out.write("			display_c();\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("	<script>\r\n");
      out.write("	function startTimer(duration, display) {\r\n");
      out.write("	    var timer = duration, minutes, seconds;\r\n");
      out.write("	    setInterval(function () {\r\n");
      out.write("	        minutes = parseInt(timer / 60, 10);\r\n");
      out.write("	        seconds = parseInt(timer % 60, 10);\r\n");
      out.write("\r\n");
      out.write("	        minutes = minutes < 10 ? \"0\" + minutes : minutes;\r\n");
      out.write("	        seconds = seconds < 10 ? \"0\" + seconds : seconds;\r\n");
      out.write("\r\n");
      out.write("	        display.textContent = minutes + \":\" + seconds;\r\n");
      out.write("\r\n");
      out.write("	        if (--timer < 0) {\r\n");
      out.write("	            timer = duration;\r\n");
      out.write("	        }\r\n");
      out.write("	    }, 1000);\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	window.onload = function () {\r\n");
      out.write("		display_ct();\r\n");
      out.write("	    var fiveMinutes = 60 * 5,\r\n");
      out.write("	        display = document.querySelector('#time');\r\n");
      out.write("	    startTimer(fiveMinutes, display);\r\n");
      out.write("	};\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
